[versions]
# https://developer.android.com/build/releases/gradle-plugin
agp = "8.4.0"
# https://github.com/JetBrains/kotlin/releases
kotlin = "1.9.23"
# Allows suspending functions
# https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "1.8.0"
# Simplifies in-app navigation
# https://developer.android.com/jetpack/androidx/releases/navigation
navigation = "2.7.7"
# Helps with keeping our view hierarchies flat
# https://developer.android.com/jetpack/androidx/releases/constraintlayout
constraintlayout = "2.1.4"
# Used by osmdroid (original prefs API is deprecated)
# https://developer.android.com/jetpack/androidx/releases/preference
preference = "1.2.1"
# Material design components
# https://github.com/material-components/material-components-android/releases
material = "1.11.0"
# Modern HTTP client
# https://github.com/square/okhttp/blob/master/CHANGELOG.md
okhttp = "5.0.0-alpha.14"
# Injection library
# https://github.com/InsertKoinIO/koin/blob/main/CHANGELOG.md
koin = "3.5.0"
# Open Street Map widget
# https://github.com/osmdroid/osmdroid/releases
osmdroid = "6.1.18"
# Map utilities
# https://github.com/locationtech/jts/releases
jts = "1.19.0"
# Charts
# https://github.com/PhilJay/MPAndroidChart/releases
mpandroidchart = "v3.1.0"
# Used to cache data and store user preferences
# https://developer.android.com/kotlin/ktx#sqlite
sqliteKtx = "2.4.0"
# Bundle SQLite binaries
# https://github.com/requery/sqlite-android/releases
# TODO remove bundled SQLite when Android bumps its deps
# > The JSON functions and operators are built into SQLite by default, as of SQLite version 3.38.0 (2022-02-22).
# API 33 -> 3.32
# API 34 -> 3.39 (~45% of our install base)
# https://www.sqlite.org/json1.html
sqlite = "3.45.0"
# Used to download, cache and display images
# https://github.com/coil-kt/coil/releases
coil = "2.6.0"
# Background job scheduler
# Used to fetch new data in background
# https://developer.android.com/jetpack/androidx/releases/work
work = "2.9.0"
# Common test dependencies
# https://junit.org/junit4/
junit = "4.13.2"
# https://mvnrepository.com/artifact/org.json/json
json = "20240303"

[libraries]
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqliteKtx" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines", version.ref = "okhttp" }
okhttp-brotli = { group = "com.squareup.okhttp3", name = "okhttp-brotli", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
osmdroid = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }
jts = { module = "org.locationtech.jts:jts-core", version.ref = "jts" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
sqlite = { module = "com.github.requery:sqlite-android", version.ref = "sqlite" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

