[versions]
# https://developer.android.com/build/releases/gradle-plugin
agp = "8.4.0"
# https://github.com/JetBrains/kotlin/releases
kotlin = "1.9.23"
# Allows suspending functions
# https://github.com/Kotlin/kotlinx.coroutines/releases
coroutines = "1.8.0"
# Simplifies in-app navigation
# https://developer.android.com/jetpack/androidx/releases/navigation
navigation = "2.7.7"
# Helps with keeping our view hierarchies flat
# https://developer.android.com/jetpack/androidx/releases/constraintlayout
constraintlayout = "2.1.4"
# Used by osmdroid (original prefs API is deprecated)
# https://developer.android.com/jetpack/androidx/releases/preference
preference = "1.2.1"
# Material design components
# https://github.com/material-components/material-components-android/releases
material = "1.12.0"
# Modern HTTP client
# https://github.com/square/okhttp/blob/master/CHANGELOG.md
okhttp = "5.0.0-alpha.14"
# Injection library
# https://github.com/InsertKoinIO/koin/blob/main/CHANGELOG.md
koin = "3.5.0"
# Open Street Map widget
# https://github.com/osmdroid/osmdroid/releases
osmdroid = "6.1.18"
# Map utilities
# https://github.com/locationtech/jts/releases
jts = "1.19.0"
# Charts
# https://github.com/PhilJay/MPAndroidChart/releases
mpandroidchart = "v3.1.0"
# Used to cache data and store user preferences
# https://developer.android.com/kotlin/ktx#sqlite
sqlite = "2.5.0-alpha02"
# Used to download, cache and display images
# https://github.com/coil-kt/coil/releases
coil = "2.6.0"
# Background job scheduler
# Used to fetch new data in background
# https://developer.android.com/jetpack/androidx/releases/work
work = "2.10.0-alpha02"
# TODO remove when work bumps its dep (an old version causes crash on startup)
room = "2.7.0-alpha02"
# Common test dependencies
# https://junit.org/junit4/
junit = "4.13.2"
# https://mvnrepository.com/artifact/org.json/json
json = "20240303"

[libraries]
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-sqlite = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room = { module = "androidx.room:room-runtime", version.ref = "room" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp-coroutines = { group = "com.squareup.okhttp3", name = "okhttp-coroutines", version.ref = "okhttp" }
okhttp-brotli = { group = "com.squareup.okhttp3", name = "okhttp-brotli", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
osmdroid = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroid" }
jts = { module = "org.locationtech.jts:jts-core", version.ref = "jts" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
coil-core = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
