name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run verification tasks
        run: ./gradlew check

      - name: Bundle the latest data snapshot
        run: ./gradlew bundleData

      - name: Assemble APKs
        run: ./gradlew assemble

      - name: Create preview release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 'preview'
          prerelease: true
          title: 'preview'
          files: app/build/outputs/apk/fdroidSelfSigned/release/app-*.apk
